openapi: 3.0.0
info:
  title: User and Role API
  version: 1.0.0
components:
  schemas:
    Role:
      type: object
      properties:
        role_name:
          type: string
        description:
          type: string
    ChangeUserRole:
      type: object
      properties:
        user_id:
          type: integer
        role_name:
          type: string

paths:
  /api/v1/roles:
    get:
      tags:
        - Role
      summary: Get all roles
      operationId: getRoles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
  /api/v1/users/change-role:
    put:
      tags:
        - User
      summary: Change user role
      operationId: changeUserRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeUserRole'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
